

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-mainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-mainapp
  template:
    metadata:
      labels:
        app: arcadia-mainapp
    spec:
      containers:
        - name: arcadia-mainapp
          image: https://registry.gitlab.com/arcadia-application/main-app/mainapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-mainapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-mainapp
